spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Wzh123.

server:
  port: 8081
  shutdown: graceful

# 指定actuator端口和地址
management:
  server:
    port: 9001